import { LegalPage } from '@/components/LegalPage'

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" effectiveDate="January 1, 2025">
      <p>
        Thank you for trusting EventDBX with your application telemetry and
        account data. This privacy policy explains what information we collect,
        why we collect it, and the controls you have over your data when you
        visit our website, run the EventDBX CLI, or interact with any of our
        services.
      </p>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          1. Information we collect
        </h2>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>
            <strong>Account details.</strong> Name, email address,
            authentication identifiers, and organization metadata you provide
            when creating an account.
          </li>
          <li>
            <strong>Product telemetry.</strong> Diagnostic events generated by
            EventDBX workloads, including cluster health, request volume, and
            anonymized performance metrics.
          </li>
          <li>
            <strong>Support content.</strong> Conversations, attachments, or log
            files you voluntarily send to our support team for troubleshooting.
          </li>
          <li>
            <strong>Website data.</strong> Standard analytics such as IP
            addresses, browser information, and referring URLs to protect the
            service and improve documentation.
          </li>
        </ul>
        <p>
          EventDBX never sells personal data and does not ingest end-user
          payloads from your customers unless you explicitly transmit those
          records to our cloud tier.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          2. How we use information
        </h2>
        <p>We process collected data only for legitimate business purposes:</p>
        <ol className="list-decimal space-y-1 pl-6 text-gray-300">
          <li>Operating the EventDBX control plane and managed clusters.</li>
          <li>
            Improving reliability, debugging performance regressions, and
            planning new features.
          </li>
          <li>
            Communicating important updates such as security advisories and
            product announcements.
          </li>
          <li>
            Meeting legal obligations, including responding to lawful requests
            from regulators.
          </li>
        </ol>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">
          3. Data retention and deletion
        </h2>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>
            Account records are retained while your subscription remains active
            and for up to 90 days after cancellation unless you request earlier
            deletion.
          </li>
          <li>
            Event telemetry stored in our managed queues is automatically purged
            after 30 days unless you opt into archival storage.
          </li>
          <li>
            Backups of production systems are encrypted and destroyed on a
            rolling 35-day schedule.
          </li>
        </ul>
        <p>
          You may request deletion at any time by emailing privacy@eventdbx.com.
          We will confirm completion once legally permitted.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">4. Your rights</h2>
        <p>
          Depending on your location, you may have the right to access, correct,
          export, or delete personal data. We honor requests made through:
        </p>
        <ul className="list-disc space-y-1 pl-6 text-gray-300">
          <li>
            <strong>Email:</strong> privacy@eventdbx.com
          </li>
          <li>
            <strong>In-product portal:</strong> Navigate to Settings → Privacy
            inside the EventDBX console.
          </li>
        </ul>
        <p>
          We will verify the requestor’s identity before sharing or deleting
          data.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">5. Security</h2>
        <p>
          EventDBX encrypts data at rest and in transit, enforces single sign-on
          for internal tools, and performs regular penetration tests. Access to
          production systems is tightly logged and restricted to the on-call
          engineering team.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">6. Updates</h2>
        <p>
          We may revise this policy to reflect new regulations or features.
          Material changes will be announced at least 30 days in advance via
          email and the product changelog. Continued use of EventDBX after
          changes go into effect constitutes acceptance of the updated policy.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-base font-semibold text-white">7. Contact</h2>
        <p>
          Questions about this privacy policy or how we handle data? Contact us
          at <strong>privacy@eventdbx.com</strong> or send a letter to
          OM.Network,LLC dba EventDBX, 5428 S Regal St, Spokane, WA 99223-9998,
          USA.
        </p>
      </section>
    </LegalPage>
  )
}
